const translations = {
    fa: {
        "company-name": "شرکت نرم‌افزار گستران تارتنک",
        "tagline": "راهکاری مطمئن برای توسعه، پشتیبانی و به‌روزرسانی نرم‌افزار شما",
        "about-link": "درباره ما",
        "services-link": "خدمات",
        "pricing-link": "تعرفه‌ها",
        "faq-link": "سوالات متداول",
        "contact-link": "تماس با ما",
        "about-title": "درباره ما",
        "about-content": "تجربه سال‌ها توسعه نرم‌افزار سفارشی برای استارت‌آپ‌ها و شرکت‌های مختلف به ما نشان داد که مشکل اصلی آن‌ها در عدم دسترسی به تیم فنی مستقر و پشتیبانی لحظه‌ای است. امروز ده‌ها شرکت موفق از خدمات ما در مدیریت تیم‌های فنی و نظارت بر توسعه نرم‌افزار خود استفاده می‌کنند.",
        "services-title": "خدمات ما",
        "service-1": "آنالیز پروژه و نرم‌افزار: بررسی سورس‌کد، تکنولوژی‌ها و ارائه گزارش وضعیت فعلی نرم‌افزار.",
        "service-2": "تشکیل و استقرار تیم فنی: گزینش و آموزش بهترین برنامه‌نویسان برای شرکت شما.",
        "service-3": "مدیریت و نظارت فنی: نظارت بر تیم‌های مستقر به‌عنوان تک لید فنی.",
        "service-4": "خدمات جانبی: DevOps، مارکتینگ، سئو و آموزش تیم‌های داخلی.",
        "pricing-title": "تعرفه‌ها",
        "pricing-1": "آنالیز و تشکیل تیم فنی: ۷۰ میلیون تومان ماهانه (بین ۲ تا ۵ ماه)",
        "pricing-2": "مدیریت و نظارت ماهانه: ۲۰ میلیون تومان برای تک لید فنی + ۱۰ میلیون تومان برای هر برنامه‌نویس مستقر",
        "pricing-3": "خدمات جانبی: قیمت‌گذاری بر اساس نوع خدمات",
        "faq-title": "سوالات متداول",
        "faq-1": "آیا می‌توانیم تیم برنامه‌نویس خودمان را مستقر کنیم؟ بله، فرآیند گزینش و استقرار توسط ما انجام می‌شود.",
        "faq-2": "آیا برای جذب نیروی فنی چالشی داریم؟ خیر، تمام فرآیند جذب و گزینش توسط تیم ما مدیریت می‌شود.",
        "faq-3": "آیا تکنولوژی مورد استفاده ما اهمیت دارد؟ خیر، ما از هر تکنولوژی که در حال حاضر استفاده می‌کنید، پشتیبانی می‌کنیم.",
        "contact-title": "تماس با ما",
        "address": "آدرس: ایران، تهران، نیاوران، منظریه ۲، بت‌بست نظر، پلاک ۱۱، واحد ۲",
        "phone": "شماره تماس: +98 21 2228 6639",
        "email": "ایمیل: info@tartank.com",
        "footer-text": "© 2025 نرم‌افزار گستران تارتنک. تمامی حقوق محفوظ است.",
        "recommendations-title": "توصیه‌نامه‌ها",
        "recommendation-1-title": "توصیه‌نامه شرکت پالیز",
        "recommendation-2-title": "توصیه‌نامه شرکت distriqt",
        "recommendation-3-title": "توصیه‌نامه موسسه علامه حلی",
        "recommendation-4-title": "موسسه ستاره هنر",
        "recommendation-5-title": "سپهرینو",
        "recommendation-6-title": "همآپ",
        "view-pdf": "مشاهده PDF"
    },
    en: {
        "company-name": "Tartank Software Solutions",
        "tagline": "A reliable solution for developing, maintaining, and updating your software",
        "about-link": "About Us",
        "services-link": "Services",
        "pricing-link": "Pricing",
        "faq-link": "FAQ",
        "contact-link": "Contact",
        "about-title": "About Us",
        "about-content": "Years of experience in custom software development for startups and various companies showed us that their main issue is the lack of an on-site technical team and real-time support. Today, dozens of successful companies use our services for managing their technical teams and supervising software development.",
        "services-title": "Our Services",
        "service-1": "Project and Software Analysis: Reviewing source code, technologies, and providing a current status report.",
        "service-2": "Technical Team Formation and Deployment: Selecting and training the best developers for your company.",
        "service-3": "Technical Management and Supervision: Supervising on-site teams as a tech lead.",
        "service-4": "Additional Services: DevOps, marketing, SEO, and internal team training.",
        "pricing-title": "Pricing",
        "pricing-1": "Project Analysis & Team Formation: $1,199 per month (2 to 5 months)",
        "pricing-2": "Monthly Management & Supervision: $429 for tech lead + $209 for each on-site developer",
        "pricing-3": "Additional Services: Pricing based on the service type",
        "faq-title": "FAQ",
        "faq-1": "Can we deploy our own development team? Yes, the selection and deployment process is managed by us.",
        "faq-2": "Do we face challenges in recruiting technical staff? No, the entire recruitment and selection process is managed by our team.",
        "faq-3": "Does the technology we use matter? No, we support any technology you are currently using.",
        "contact-title": "Contact Us",
        "address": "Address: Iran, Tehran, Niavaran, Manzariyeh 2, Bat-Bast Nazar, No. 11, Unit 2",
        "phone": "Phone: +98 21 2228 6639",
        "email": "Email: info@tartank.com",
        "footer-text": "© 2025 Tartank Software Solutions. All rights reserved.",
        "recommendations-title": "Recommendations",
        "recommendation-1-title": "Recommendation from Paliz Co.",
        "recommendation-2-title": "Recommendation from DISTRIQT PTY LTD",
        "recommendation-3-title": "Recommendation from MHelli Institute",
        "recommendation-4-title": "Filmnab",
        "recommendation-5-title": "Sepehrino",
        "recommendation-6-title": "Hamup",
        "view-pdf": "View PDF"
    },
    ar: {
        "company-name": "تارتانك لحلول البرمجيات",
        "tagline": "حل موثوق لتطوير وصيانة وتحديث برامجك",
        "about-link": "من نحن",
        "services-link": "الخدمات",
        "pricing-link": "الأسعار",
        "faq-link": "الأسئلة الشائعة",
        "contact-link": "اتصل بنا",
        "about-title": "من نحن",
        "about-content": "أظهرت لنا سنوات من الخبرة في تطوير البرمجيات المخصصة للشركات الناشئة والشركات المختلفة أن مشكلتهم الرئيسية هي عدم وجود فريق تقني مقيم ودعم فوري. اليوم، تستخدم عشرات الشركات الناجحة خدماتنا لإدارة فرقها التقنية والإشراف على تطوير البرمجيات.",
        "services-title": "خدماتنا",
        "service-1": "تحليل المشاريع والبرمجيات: مراجعة الكود المصدري، والتقنيات، وتقديم تقرير عن الوضع الحالي.",
        "service-2": "تكوين ونشر الفريق التقني: اختيار وتدريب أفضل المطورين لشركتك.",
        "service-3": "الإدارة والإشراف الفني: الإشراف على الفرق المقيمة كقائد تقني.",
        "service-4": "الخدمات الإضافية: DevOps، التسويق، تحسين محركات البحث، وتدريب الفرق الداخلية.",
        "pricing-title": "الأسعار",
        "pricing-1": "تحليل المشروع وتكوين الفريق: 1,099 دولار شهريًا (بين شهرين إلى خمسة أشهر)",
        "pricing-2": "الإدارة والإشراف الشهري: 389 دولار للقائد التقني + 199 دولار لكل مطور مقيم",
        "pricing-3": "الخدمات الإضافية: التسعير يعتمد على نوع الخدمة",
        "faq-title": "الأسئلة الشائعة",
        "faq-1": "هل يمكننا نشر فريقنا الخاص من المطورين؟ نعم، يتم إدارة عملية الاختيار والنشر من قبلنا.",
        "faq-2": "هل نواجه تحديات في توظيف الكوادر التقنية؟ لا، يتم إدارة عملية التوظيف والاختيار بالكامل من قبل فريقنا.",
        "faq-3": "هل التكنولوجيا التي نستخدمها مهمة؟ لا، نحن ندعم أي تقنية تستخدمها حاليًا.",
        "contact-title": "اتصل بنا",
        "address": "العنوان: إيران، طهران، نياوران، منزريه 2، بت-بست نظر، رقم 11، الوحدة 2",
        "phone": "الهاتف: +98 21 2228 6639",
        "email": "البريد الإلكتروني: info@tartank.com",
        "footer-text": "© 2025 تارتانك لحلول البرمجيات. جميع الحقوق محفوظة.",
        "recommendations-title": "التوصيات",
        "recommendation-1-title": "Recommendation from Paliz Co.",
        "recommendation-2-title": "Recommendation from DISTRIQT PTY LTD",
        "recommendation-3-title": "Recommendation from MHelli Institute",
        "recommendation-4-title": "Filmnab",
        "recommendation-5-title": "Sepehrino",
        "recommendation-6-title": "Hamup",
        "view-pdf": "عرض PDF"
    },
    fr: {
        "company-name": "Solutions Logiciels Tartank",
        "tagline": "Une solution fiable pour le développement, la maintenance et la mise à jour de votre logiciel",
        "about-link": "À propos de nous",
        "services-link": "Services",
        "pricing-link": "Tarifs",
        "faq-link": "FAQ",
        "contact-link": "Contact",
        "about-title": "À propos de nous",
        "about-content": "Des années d'expérience dans le développement de logiciels personnalisés pour des startups et diverses entreprises nous ont montré que leur principal problème est l'absence d'une équipe technique sur place et d'un support en temps réel. Aujourd'hui, des dizaines d'entreprises prospères utilisent nos services pour gérer leurs équipes techniques et superviser le développement de logiciels.",
        "services-title": "Nos services",
        "service-1": "Analyse de projet et de logiciel : Revue du code source, des technologies et rapport sur l'état actuel.",
        "service-2": "Formation et déploiement d'équipe technique : Sélection et formation des meilleurs développeurs pour votre entreprise.",
        "service-3": "Gestion et supervision technique : Supervision des équipes sur place en tant que tech lead.",
        "service-4": "Services supplémentaires : DevOps, marketing, SEO et formation des équipes internes.",
        "pricing-title": "Tarifs",
        "pricing-1": "Analyse de projet et formation d'équipe : 1 099 € par mois (entre 2 et 5 mois)",
        "pricing-2": "Gestion et supervision mensuelle : 389 € pour le tech lead + 199 € pour chaque développeur sur site",
        "pricing-3": "Services supplémentaires : Tarification selon le type de service",
        "faq-title": "FAQ",
        "faq-1": "Pouvons-nous déployer notre propre équipe de développement ? Oui, le processus de sélection et de déploiement est géré par nos soins.",
        "faq-2": "Rencontrons-nous des difficultés pour recruter du personnel technique ? Non, l'ensemble du processus de recrutement et de sélection est géré par notre équipe.",
        "faq-3": "La technologie que nous utilisons est-elle importante ? Non, nous prenons en charge toute technologie que vous utilisez actuellement.",
        "contact-title": "Contactez-nous",
        "address": "Adresse : Iran, Téhéran, Niavaran, Manzariyeh 2, Bat-Bast Nazar, N° 11, Unité 2",
        "phone": "Téléphone : +98 21 2228 6639",
        "email": "E-mail : info@tartank.com",
        "footer-text": "© 2025 Solutions Logiciels Tartank. Tous droits réservés.",
        "recommendations-title": "Recommandations",
        "recommendation-1-title": "Recommendation from Paliz Co.",
        "recommendation-2-title": "Recommendation from DISTRIQT PTY LTD",
        "recommendation-3-title": "Recommendation from MHelli Institute",
        "recommendation-4-title": "Filmnab",
        "recommendation-5-title": "Sepehrino",
        "recommendation-6-title": "Hamup",
        "view-pdf": "Voir le PDF"
    },
    es: {
        "company-name": "Soluciones de Software Tartank",
        "tagline": "Una solución confiable para el desarrollo, mantenimiento y actualización de su software",
        "about-link": "Sobre nosotros",
        "services-link": "Servicios",
        "pricing-link": "Precios",
        "faq-link": "Preguntas frecuentes",
        "contact-link": "Contacto",
        "about-title": "Sobre nosotros",
        "about-content": "Años de experiencia en el desarrollo de software personalizado para startups y diversas empresas nos han demostrado que su principal problema es la falta de un equipo técnico local y soporte en tiempo real. Hoy en día, decenas de empresas exitosas utilizan nuestros servicios para gestionar sus equipos técnicos y supervisar el desarrollo de software.",
        "services-title": "Nuestros servicios",
        "service-1": "Análisis de proyectos y software: Revisión del código fuente, tecnologías y reporte del estado actual.",
        "service-2": "Formación y despliegue de equipos técnicos: Selección y formación de los mejores desarrolladores para su empresa.",
        "service-3": "Gestión y supervisión técnica: Supervisión de los equipos locales como líder técnico.",
        "service-4": "Servicios adicionales: DevOps, marketing, SEO y formación de equipos internos.",
        "pricing-title": "Precios",
        "pricing-1": "Análisis de proyectos y formación de equipo: 1,199 USD al mes (entre 2 y 5 meses)",
        "pricing-2": "Gestión y supervisión mensual: 429 USD para el líder técnico + 209 USD para cada desarrollador local",
        "pricing-3": "Servicios adicionales: Precio según el tipo de servicio",
        "faq-title": "Preguntas frecuentes",
        "faq-1": "¿Podemos desplegar nuestro propio equipo de desarrollo? Sí, el proceso de selección y despliegue lo gestionamos nosotros.",
        "faq-2": "¿Tenemos desafíos para reclutar personal técnico? No, todo el proceso de reclutamiento y selección está gestionado por nuestro equipo.",
        "faq-3": "¿Es importante la tecnología que utilizamos? No, apoyamos cualquier tecnología que esté utilizando actualmente.",
        "contact-title": "Contáctenos",
        "address": "Dirección: Irán, Teherán, Niavaran, Manzariyeh 2, Bat-Bast Nazar, No. 11, Unidad 2",
        "phone": "Teléfono: +98 21 2228 6639",
        "email": "Correo electrónico: info@tartank.com",
        "footer-text": "© 2025 Soluciones de Software Tartank. Todos los derechos reservados.",
        "recommendations-title": "Recomendaciones",
        "recommendation-1-title": "Recommendation from Paliz Co.",
        "recommendation-2-title": "Recommendation from DISTRIQT PTY LTD",
        "recommendation-3-title": "Recommendation from MHelli Institute",
        "recommendation-4-title": "Filmnab",
        "recommendation-5-title": "Sepehrino",
        "recommendation-6-title": "Hamup",
        "view-pdf": "Ver PDF"
    },
    de: {
        "company-name": "Tartank Software Lösungen",
        "tagline": "Eine zuverlässige Lösung für die Entwicklung, Wartung und Aktualisierung Ihrer Software",
        "about-link": "Über uns",
        "services-link": "Dienstleistungen",
        "pricing-link": "Preise",
        "faq-link": "Häufige Fragen",
        "contact-link": "Kontakt",
        "about-title": "Über uns",
        "about-content": "Jahrelange Erfahrung in der Entwicklung maßgeschneiderter Software für Start-ups und verschiedene Unternehmen hat uns gezeigt, dass ihr Hauptproblem der Mangel an einem vor Ort ansässigen technischen Team und Echtzeit-Support ist. Heute nutzen Dutzende erfolgreicher Unternehmen unsere Dienstleistungen zur Verwaltung ihrer technischen Teams und zur Überwachung der Softwareentwicklung.",
        "services-title": "Unsere Dienstleistungen",
        "service-1": "Projekt- und Softwareanalyse: Überprüfung des Quellcodes, der Technologien und Erstellung eines Statusberichts.",
        "service-2": "Bildung und Einsatz von technischen Teams: Auswahl und Schulung der besten Entwickler für Ihr Unternehmen.",
        "service-3": "Technisches Management und Überwachung: Überwachung der vor Ort ansässigen Teams als Tech-Lead.",
        "service-4": "Zusätzliche Dienstleistungen: DevOps, Marketing, SEO und Schulung interner Teams.",
        "pricing-title": "Preise",
        "pricing-1": "Projektanalyse und Teambildung: 1.349 € pro Monat (2 bis 5 Monate)",
        "pricing-2": "Monatliche Verwaltung und Überwachung: 479 € für den Tech-Lead + 239 € für jeden vor Ort ansässigen Entwickler",
        "pricing-3": "Zusätzliche Dienstleistungen: Preisgestaltung je nach Dienstleistungstyp",
        "faq-title": "Häufige Fragen",
        "faq-1": "Können wir unser eigenes Entwicklerteam einsetzen? Ja, der Auswahl- und Einsatzprozess wird von uns durchgeführt.",
        "faq-2": "Gibt es Herausforderungen bei der Rekrutierung von technischem Personal? Nein, der gesamte Rekrutierungs- und Auswahlprozess wird von unserem Team verwaltet.",
        "faq-3": "Ist die von uns verwendete Technologie wichtig? Nein, wir unterstützen jede Technologie, die Sie derzeit verwenden.",
        "contact-title": "Kontakt",
        "address": "Adresse: Iran, Teheran, Niavaran, Manzariyeh 2, Bat-Bast Nazar, Nr. 11, Einheit 2",
        "phone": "Telefon: +98 21 2228 6639",
        "email": "E-Mail: info@tartank.com",
        "footer-text": "© 2025 Tartank Software Lösungen. Alle Rechte vorbehalten.",
        "recommendations-title": "Empfehlungen",
        "recommendation-1-title": "Recommendation from Paliz Co.",
        "recommendation-2-title": "Recommendation from DISTRIQT PTY LTD",
        "recommendation-3-title": "Recommendation from MHelli Institute",
        "recommendation-4-title": "Filmnab",
        "recommendation-5-title": "Sepehrino",
        "recommendation-6-title": "Hamup",
        "view-pdf": "PDF anzeigen"
    },
    zh: {
        "company-name": "塔坦克软件解决方案公司",
        "tagline": "为您的软件开发、维护和更新提供可靠的解决方案",
        "about-link": "关于我们",
        "services-link": "服务",
        "pricing-link": "价格",
        "faq-link": "常见问题",
        "contact-link": "联系我们",
        "about-title": "关于我们",
        "about-content": "多年来，我们为初创企业和各种公司提供定制软件开发服务，发现他们的主要问题是缺乏驻场技术团队和实时支持。如今，数十家成功企业使用我们的服务来管理他们的技术团队并监督软件开发。",
        "services-title": "我们的服务",
        "service-1": "项目和软件分析：审核源代码、技术并提供现状报告。",
        "service-2": "技术团队组建和部署：为您的公司挑选并培训最佳开发人员。",
        "service-3": "技术管理和监督：作为技术主管监督驻场团队。",
        "service-4": "增值服务：DevOps、营销、SEO和内部团队培训。",
        "pricing-title": "价格",
        "pricing-1": "项目分析和团队组建：每月1,099美元（2至5个月）",
        "pricing-2": "每月管理和监督：技术主管389美元 + 每位驻场开发人员199美元",
        "pricing-3": "增值服务：根据服务类型定价",
        "faq-title": "常见问题",
        "faq-1": "我们可以部署自己的开发团队吗？可以，选拔和部署流程由我们管理。",
        "faq-2": "我们在招聘技术人员方面有困难吗？不会，整个招聘和选拔流程由我们的团队负责。",
        "faq-3": "我们使用的技术重要吗？不，我们支持您当前使用的任何技术。",
        "contact-title": "联系我们",
        "address": "地址：伊朗，德黑兰，尼亚瓦兰，曼扎里耶2号，Bat-Bast Nazar街11号，2单元",
        "phone": "电话：+98 21 2228 6639",
        "email": "电子邮件：info@tartank.com",
        "footer-text": "© 2025 塔坦克软件解决方案公司。保留所有权利。",
        "recommendations-title": "推荐信",
        "recommendation-1-title": "Recommendation from Paliz Co.",
        "recommendation-2-title": "Recommendation from DISTRIQT PTY LTD",
        "recommendation-3-title": "Recommendation from MHelli Institute",
        "recommendation-4-title": "Filmnab",
        "recommendation-5-title": "Sepehrino",
        "recommendation-6-title": "Hamup",
        "view-pdf": "查看PDF"
    }
      
      
};

function changeLanguage() {
    const language = document.getElementById('languageSelect').value;
    document.documentElement.lang = language;
    document.body.dir = language === 'fa' || language === 'ar' ? 'rtl' : 'ltr';
    
    const elementsToTranslate = document.querySelectorAll('[id]');
    elementsToTranslate.forEach(element => {
        const key = element.id;
        if (translations[language] && translations[language][key]) {
            if (element.tagName === 'A' || element.tagName === 'P' || element.tagName === 'DIV') {
                element.innerHTML = translations[language][key];
            } else {
                element.textContent = translations[language][key];
            }
        }
    });
}